apiVersion: apps/v1
kind: Deployment
metadata:
  name: bowhead-dfo-deployment
spec:
  selector:
    matchLabels:
      app: bowhead-dfo
  template:
    metadata:
      labels:
        app: bowhead-dfo
    spec:
      containers:
      - name: bowhead-dfo
        image: gcr.io/equivos-main/bowhead-dfo:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: bowhead-dfo-config
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bowhead-dfo-service
spec:
  type: NodePort
  selector:
    app: bowhead-dfo
  ports:
  - port: 8000
    targetPort: 8000
# this needs to be configured with an Ingress, which is defined in another repo